# Generated by Django 4.2.4 on 2023-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("clientid", models.CharField(max_length=255)),
                ("createtime", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="matters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matters", models.CharField(max_length=255)),
                ("matterid", models.CharField(max_length=255)),
                ("createtime", models.CharField(max_length=255)),
                ("clientnumber", models.CharField(max_length=255)),
                ("membernumber", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("memberid", models.CharField(max_length=255)),
                ("modifiedtime", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("requestid", models.CharField(max_length=255)),
                ("createtime", models.CharField(max_length=255)),
            ],
        ),
    ]
